### ISSUE TITLE
Shaman-Enhancement - No rules for Echo of the Elements or Maelstrom Weapon

### ISSUE THREAD

**Issue by fmanna** [Adirelle/LibPlayerSpells-1.0#73]
Spell IDs:
403 (Lightning Bolt)
421 (Chain Lightning)
8004 (Healing Surge)
60103 (Lava Lash)

Since installing the 1.8.10 update of AdiButtonAuras, I see that there are no rules for the above spells. They used to have rules for Echo of the Elements and Maelstrom Weapon-now none of my buttons flash for MW.

**Comment by fmanna** [comment]
Rolled back to 1.8.9, and the rules are available. These are the versions that include libraries.

I apologize if this is attached to the wrong project-the rules in 1.8.9 for LL and LB say LPS-SHAMAN-6.0.0-2, so I thought it was an issue with LibPlayerSpell.

**Comment by fmanna** [comment]
Manually reverting this commit solves the issue: https://github.com/Adirelle/LibPlayerSpells-1.0/commit/e61501e2444990b0aa631cb3580cd06a7ed98e71#diff-6d447fd53f61425f53efa768088d1c0b

Not sure why the committed code doesn't work.

**Comment by Adirelle** [comment]
I think the buffs have different spell ids than the entries of the spellbook. Could you enable the "debug tooltip" and tell us what the ids of the spellbook entries are for these (passive) spells?

* Maelstrom Weapon
* Tidal Wave
* Echo of Elements

**Comment by fmanna** [comment]
Maelstrom Weapon - 51530
Echo of the Elements (Enhancement) - 108283
Tidal Waves - 51564

**Comment by Rainrider** [comment]
My shaman is level 55 currently, so I can confirm the ids for Maelstrom Weapon and Tidal Waves but not for Echo of the Elements as it is a level 60 talent. It seems though that 108283 is always the talent spell id regardless of the chosen spec. So either someone confirms that or you wait until I find the time to make those 5 levels :smile:
